### ISSUE TITLE
fixing parameter: AttributeError: 'NonLinearParameter' object has no attribute 'value'

### ISSUE THREAD

**Issue by LyneVdV** [aymgal/LensModelAPI#1]
My problem is a bit messy. I would like to use the API to create a template json file for a lens system. In this template I define a lensing galaxy, with mass profile being a SIS. However, there is no SIS yet in the list of possible mass profile. Thus I wanted to create a SIE with fixed ellipticity parameters. After creating my Galaxy
`lens = Galaxy("The main deflector", 0.5,light_model=LightModel('SersicElliptical'),mass_model=MassModel('SIE'))`
I wanted to simply set the ellipticity to 0 and fix this parameter. To set the ellipticity to 0, I saw several possibilities :
`lens.mass_model.profiles[0].parameters['e1'].set_point_estimate(PointEstimate(value=0.))`
or `lens.mass_model.profiles[0].parameters['e1'].set_value(value=0.)`
The first solution does create a point_estimate and set its value to 0.
The second possibility (using `set_value`) gives me `AttributeError: 'NonLinearParameter' object has no attribute 'value'`. I think it's because, at line 67 in LensModelAPI/python/lensmodelapi/api/parameter.py, there is a if statement checking the value of self.value that doesn't exist (it's not None or anything, it just isn't defined).
When latter I try to fix a parameter with 
`lens.mass_model.profiles[0].parameters['e1'].fix()`
I have the error `AttributeError: 'NonLinearParameter' object has no attribute 'value'` for the same reason I think.

**Comment by aymgal** [comment]
Thanks @LyneVdV for reporting this bug! Indeed there was obsolete lines in there. The commit I just [pushed](https://github.com/aymgal/LensModelAPI/commit/c787b091d769b821f75e2b806f8df867cd463be2) should solve the issue hopefully. The way to go (other than setting the attribute directly) is to use the `set_point_estimate` method.

**Comment by LyneVdV** [comment]
There is still the if statement at line 100 checking self.value in the `fix(self)` function !

**Comment by aymgal** [comment]
Argh, I pushed a new commit for fixing this... sorry!

**Comment by LyneVdV** [comment]
There is still a typo self.elf.point --> self.point in the fix() function, the pull request should fix it :) (sorry for the back and forth, I hope the pull request will ease your life :) )
