### ISSUE TITLE
How to define initial estimate

### ISSUE THREAD

**Issue by LyneVdV** [aymgal/LensModelAPI#2]
I would like to use the API to create a template for a lens system. In this, I would like to write initial parameters for a mass model. In `LensModelAPI/python/lensmodelapi/api/parameter.py `, I don't see any function named `set_initial_estimate`. Is there a way to do it with the API, other than writing in the created json file later ?

**Comment by aymgal** [comment]
No indeed, there is no method to set it currently. I suggest that you attribute the value directly to the attribute `initial_estimate` with an instance of `PointEstimate`, it's totally fine 🙂

**Comment by LyneVdV** [comment]
Attributing the value directly is super easy, thanks !
