### ISSUE TITLE
List or numpy array in json files (write and read)

### ISSUE THREAD

**Issue by LyneVdV** [aymgal/LensModelAPI#8]
When writing a list or a numpy array in a json file using the API, I have 2 ways of doing it.
1) I can use `light_or_mass_profile.parameters['param_name'].set_point_estimate(PointEstimate(json.dumps(list(my_list))))`. The json.dumps allows me to have a nice display in the json file when you read it with a simple text editor (see image below). It has the disavantage that it is later considered as a string in the API (and not a list), which unables the comparison with a numpy array, for instance to see if it's inside the required boundaries. 

![Capture d’écran du 2022-01-06 14-39-54](https://user-images.githubusercontent.com/43570542/148391519-175c9188-3060-4401-9b75-afc2e0f586ed.png)

2) I can remove the json.dumps, and use `light_or_mass_profile.parameters['param_name'].set_point_estimate(PointEstimate(list(my_list)))`, which works well in the API. But if I want to have a quick look at the json file in itself, without using the API, I can not read the information (see below part of the awful display of a single list or a numpy array in the json file).

![Capture d’écran du 2022-01-06 14-30-29](https://user-images.githubusercontent.com/43570542/148390584-7f282c17-42b7-45b9-a8b1-6e71680c644e.png)

It's not really a problem of the API, it's working well with numpy arrays and list (i.e. with method 2) ), but the display and readability of the json file without the API is difficult. I don't know if it is maybe possible for users to use the json.dumps and having the counter part json.loads inside the API when lists are involved ? I am also grateful if you have any other ideas or solutions !

**Comment by aymgal** [comment]
Hmm, this is strange, I am not sure to understand what's happening with method 2. Just to make sure I understand: if you start with a numpy array, you convert it to a standard list and you set the PointEstimate with it, then the result is this non-readable mess?
Is it the same if you use the `tolist` [method](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tolist.html) from the numpy array itself?

**Comment by LyneVdV** [comment]
yes that is the issue: if I set PointEstimate of a numpy array or PointEstimate of list(numpy array), the result is this non-readable mess in the .json file. When the API is used to read the results however, it can read it perfectly (and the type is a list or a ndarray). It's like it tries to save the fact that it is / comes from a numpy array, which is a class information.
But the `np.ndarray.tolist() `works :D !! It really transform it to a json friendly list ! Thank you, that solved my issue !

**Comment by aymgal** [comment]
Perfect then ! :)
